set(LOCM3_DEVICE_SCRIPT ${llibopencm3_SOURCE_DIR}/scripts/genlink.py)
set(LOCM3_DEVICE_DATABASE ${llibopencm3_SOURCE_DIR}/ld/devices.data)
set(LOCM3_LINKER_TEMPLATE ${llibopencm3_SOURCE_DIR}/ld/linker.ld.S)
set(LOCM3_LINKER_GENERATED ${llibopencm3_SOURCE_DIR}/lib/generated.${DEVICE}.ld)
set(LOCM3_INCLUDE_DIR ${llibopencm3_SOURCE_DIR}/include)
set(LOCM3_STATIC_LIB_PREFIX ${llibopencm3_SOURCE_DIR}/lib/libopencm3_)

# Values debug print
message(VERBOSE "\nVerbose:")
message(VERBOSE "Libopencm3 device script: ${LOCM3_DEVICE_SCRIPT}")
message(VERBOSE "Libopencm3 device database: ${LOCM3_DEVICE_DATABASE}")
message(VERBOSE "Libopencm3 linker template: ${LOCM3_LINKER_TEMPLATE}")
message(VERBOSE "Libopencm3 linker script: ${LOCM3_LINKER_GENERATED}")
message(VERBOSE "Libopencm3 include dir: ${LOCM3_INCLUDE_DIR}")
message(VERBOSE "Libopencm3 static lib prefix: ${LOCM3_STATIC_LIB_PREFIX}")


message(CHECK_START "Query device info and generate linker script")
if(CMAKE_HOST_WIN32)
     execute_process( COMMAND python ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "CPPFLAGS" OUTPUT_VARIABLE LOCM3_DEVICE_DEFINES OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND python ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "CPU" OUTPUT_VARIABLE MCPU OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND python ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "FPU" OUTPUT_VARIABLE FPU_STR OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND python ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "DEFS" OUTPUT_VARIABLE DEVDEFS OUTPUT_STRIP_TRAILING_WHITESPACE)
     string(APPEND DEVDEFS " -P -E " ${LOCM3_LINKER_TEMPLATE} " " -o " " ${LOCM3_LINKER_GENERATED})
     separate_arguments(GEN_LD UNIX_COMMAND ${DEVDEFS})
     execute_process(COMMAND ${CMAKE_C_COMPILER} ${GEN_LD})
else()
     execute_process( COMMAND ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "CPPFLAGS" OUTPUT_VARIABLE LOCM3_DEVICE_DEFINES OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "CPU" OUTPUT_VARIABLE MCPU OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "FPU" OUTPUT_VARIABLE FPU_STR OUTPUT_STRIP_TRAILING_WHITESPACE)
     execute_process( COMMAND ${LOCM3_DEVICE_SCRIPT} ${LOCM3_DEVICE_DATABASE} ${DEVICE} "DEFS" OUTPUT_VARIABLE DEVDEFS OUTPUT_STRIP_TRAILING_WHITESPACE)
     string(APPEND DEVDEFS " -P -E " ${LOCM3_LINKER_TEMPLATE} " " -o " " ${LOCM3_LINKER_GENERATED})
     separate_arguments(GEN_LD UNIX_COMMAND ${DEVDEFS})
     execute_process(COMMAND ${CMAKE_C_COMPILER} ${GEN_LD})
endif()
# Values debug print
message(VERBOSE "\nVerbose:")
message(VERBOSE "Device defines: ${DEVDEFS}")
message(VERBOSE "Ld script generation parameters: ${GEN_LD}")
message(CHECK_PASS "Done")


message(CHECK_START "Make target definitions")
string(TOLOWER ${LOCM3_DEVICE_DEFINES} LOCM3_DEVICE_DEFINES_LOWCASE)
string(REPLACE -d "" LOCM3_DEVICE_STRING ${LOCM3_DEVICE_DEFINES_LOWCASE})
string(REPLACE " " ";" LOCM3_DEVICE_LIST ${LOCM3_DEVICE_STRING})
list(GET LOCM3_DEVICE_LIST 0 LOCM3_DEVICE_SERIE)
string(REPLACE stm32 stm32/ LOCM3_TARGET ${LOCM3_DEVICE_SERIE})
# Values debug print
message(VERBOSE "\nVerbose:")
message(VERBOSE "Libopencm3 build target: ${LOCM3_TARGET}")
message(VERBOSE "Libopencm3 linker script: ${LOCM3_LINKER_GENERATED}")


set(THUMB_CORES cortex-m0 cortex-m0plus cortex-m3 cortex-m4 cortex-m7)
if(MCPU IN_LIST THUMB_CORES)
  set(MTHUMB "-mthumb")
endif()
string(PREPEND MCPU "-mcpu=")


if(FPU_STR STREQUAL "soft")
  set(MFLOAT_ABI "-msoft-float")
elseif(FPU_STR STREQUAL "hard-fpv4-sp-d16")
  set(MFLOAT_ABI "-mfloat-abi=hard")
  set(MFPU "-mfpu=fpv4-sp-d16")
elseif(FPU_STR STREQUAL "hard-fpv5-sp-d16")
  set(MFLOAT_ABI "-mfloat-abi=hard")
  set(MFPU "-mfpu=fpv5-sp-d16")
else()
  message(WARNING "Float ABI not defined!")
endif()
message(CHECK_PASS "Done")
